### ISSUE TITLE
Badge rendering issue in README

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1087]
Screenshot of the issue below. Also viewable via [this link]( https://github.com/conda-forge/adaptive-scheduler-feedstock#current-build-status ).

<hr>

<img width="610" alt="Screen Shot 2019-06-10 at 5 46 58 PM" src="https://user-images.githubusercontent.com/3019665/59229195-c1e01c00-8ba7-11e9-96a4-b8b5f88486a7.png">

**Comment by refraction-ray** [comment]
Hi, any progress on this issue? I can confirm this is due to https://github.com/conda-forge/conda-smithy/blob/47de4701fe7ecf77fbcee06f6ebb8d22639e8099/conda_smithy/templates/README.md.tmpl#L159-L161
Basically, these lines in template for readme lack tr and td html syntax. I guess the following code should fix this.
```
 <tr>
    <td>ppc64le</td>
    <td>
      <img src="{{ shield }}badge/ppc64le-disabled-lightgrey.svg" alt="ppc64le disabled">
    </td>
  </tr>
```
Any suggestions? Or should I open a PR for this?

**Comment by isuruf** [comment]
> Or should I open a PR for this?

Yes, please.

**Comment by jakirkham** [comment]
Thanks @refraction-ray! 😄
