### ISSUE TITLE
Add support for Github Actions

### ISSUE THREAD

**Issue by hadim** [conda-forge/conda-smithy#1361]
Apologize if this topic has already been covered somewhere (couldn't find it).

Would that be possible to add Github Actions as a package builder CI service in conda-smithy?

**Comment by hadim** [comment]
Asking for a private conda forge we are running and switching to GA would centralize all our CIs to the same place.

**Comment by beckermr** [comment]
Yes this has been discussed and I really appreciate you opening this issue!

TL;DR We can support this, but have not put a bunch of time into it. 

One issue is rerendering, where changes to the workflow files cannot be pushed via the github token in github actions.

**Comment by hadim** [comment]
> One issue is rerendering, where changes to the workflow files cannot be pushed via the github token in github actions.

I don't understand why isn't that possible?

**Comment by beckermr** [comment]
It is a security thing on GitHub's side. They don't allow the GITHUB_TOKEN in the actions to push on rerendering if the workflows files are edited. This is only an issue for conda-forge and may not be one for a private org.

**Comment by hadim** [comment]
Oh, I see you're talking about the `GITHUB_TOKEN` provided by default in GA workflows. What prevents you to generate your own token or use a bot user/password? I agree it's not ideal but that could do the job.

**Comment by isuruf** [comment]
I think we are talking about two different issues. For github actions as a CI service, we don't need to do any rerendering or push files into the git repo. We don't do it with other CI.

**Comment by beckermr** [comment]
indeed @isuruf - what I am saying though is that for conda-forge, we'll need to disable github as a CI for now until we solve the conda-forge rerendering issue

as I said above, this would not be an issue for a private channel

**Comment by isuruf** [comment]
True. For conda-forge, github CI doesn't offer much, but for private orgs it'll be easier.

**Comment by CAM-Gerlach** [comment]
@beckermr Now that Travis has all but dropped support for open source and projects are moving to Github Actions en-masse, is there any thought to moving forward on this? What would be the steps needed to add this support? Our use case (the Spyder projects) would not only be for CF  packaging but more broadly as a useful tool with `ci-skeleton` to abstract most of the nuts and bolts of maintaining CI configuration and infrastructure.

**Comment by isuruf** [comment]
@CAM-Gerlach, PRs are welcome to add this. You would need to add a function like https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/configure_feedstock.py#L1063.

**Comment by beckermr** [comment]
Yup prs welcome. Note as stated above we won't be using GitHub actions on conda-forge itself because of token permission issues and the fact that some of our automated services depend on GitHub actions and long running jobs would cripple them.

**Comment by leycec** [comment]
TravisCI has become increasingly unreliable **even for basic conda-forge use.** This depresses the nostalgic netizen in me, because TravisCI used to be *such* a remarkable first-to-market QA vendor.

But that was before the Idera buyout. This is now. Courtesy conda-forge/pydot-feedstock#14:

> I also noticed a few days ago that **some TravisCI ppc64le instances were hanging at "Step 3 Booting Virtual Machine".** I solved it by stopping and restarting those particular jobs (not the entire build) and in the end they all went through.

> There are a few bad apples or **some oddity with docker with TravisCI.** Anyway, after a few re-triggers with my :crossed_fingers:, CI has finally passed. I hope the one on master doesn't give me the same amount of pain.

That's... *not good.* The one thing everyone needs to be robust here is CI/CD. At the end of the day, CI/CD is really all that conda-forge is.

Of course, no one expects a full-stop transition from TravisCI to GitHub Actions to happen overnight – or even in several months. But given the downward trajectory of TravisCI's open-source offering, it might be pragmatic to slowly begin broaching the subject more proactively.

Just sayin'. You know.

Anyway! As always, conda-forge rocks. We at @beartype remain humbly indebted to the thankless man-hours that everyone puts in to the just cause of portable Python packaging. Winter fireworks for all! :fireworks:

**Comment by chrisburr** [comment]
This issue is about adding support for GitHub Actions for external users of conda-smithy. GitHub actions won't be used for conda-forge package builds for the reasons stated above (authentication, limited resources, high priority usage by the automated services).

Travis is currently only used for native ppc64le builds and, to the best of my knowledge, Travis is the only option for native ppc64le CI builds. Alternatively it is possible for feedstocks to use cross-compilation or emulation from Azure pipelines however these both come with their own pain points.

**Comment by jakirkham** [comment]
Isuru put up an implementation in PR ( https://github.com/conda-forge/conda-smithy/pull/1461 ). Though there may be additional things that people will want to add to it

**Comment by CAM-Gerlach** [comment]
Fantastic, thanks @isuruf and @jakirkham ! I'll be sure to check it out soon; I assume a new version will be released shortly containing this feature?

**Comment by hadim** [comment]
Thanks for the work done here @isuruf! I will try to test it on our private forge soon enough.

**Comment by jakirkham** [comment]
To be clear, I just clicked the green button. Isuru did all the work 🙂
