### ISSUE TITLE
Azure: artifact upload error due to filename truncation 

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-smithy#1466]
See for example https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=295780&view=results.

Many Linux CI tests there failed at the artifact upload stage. The reason is that there's a 80-character limitation in the uploaded filename set somewhere (found by @chrisburr), so their filenames got truncated and collided with each other. 

I think given the growing build complexity (cdt name, cuda, etc) this hard limit should be relaxed?

**Comment by ryanvolz** [comment]
The 80-character truncation that is done by conda-smithy is because there is an actual limit to the artifact name length for Azure. It wasn't exactly 80, but we couldn't find any Azure docs on what the length actually is so we went with 80 because it worked. Anything longer than whatever the actual limit is, and the artifacts will fail to upload in a not-so-different manner from what you're seeing. See #1390.

I think the real fix here would be to ensure that the shortened names are unique. It looks like there is some somewhat recent code adding a `short_config_name` that could perhaps be applied to the artifact name (either using a similar technique or directly incorporating that same `short_config_name` variable).

**Comment by leofang** [comment]
Should be fixed by #1478.
