### ISSUE TITLE
Common functionality to manage feedstocks

### ISSUE THREAD

**Issue by 183amir** [conda-forge/conda-smithy#149]
I would like to see some features on conda-smithy to help me manage feedstocks:

- [ ] Increase build number. set build number to a number.
- [ ] Increase build number for libraries that depend on this during build.
- [ ] Update to latest pypi version.
- [ ] check if some dependencies are pinned in conda-forge and suggest to pin them.
- [ ] for a recipe that needs to be submitted as a pull request to `staged-recipes`, check if dependencies are available in mentioned conda channels and once they become available open a pull automatically.
- [ ] convert pypi packages to conda recipes that conform conda-forge standards.

And possibly more. Do you think conda-smithy would be a good place to have at least some of these features?

**Comment by pelson** [comment]
> Do you think conda-smithy would be a good place to have at least some of these features?

Yes and no. Yes because they are in one place. No because I think they would make useful *small* standalone packages which can be tested easily. My inclination: have a go at implementing some of these in separate repos (you can always make use of conda-smithy's API) and we can integrate into conda-forge once we are happy with them.

I'm happy to lend any advice if necessary.

Thanks @183amir!

**Comment by jakirkham** [comment]
As the decision is these should live elsewhere, I'm going to close this. However, that is not to say there is no interest in these. In fact it is quite the contrary. Maybe the remainder of discussion here can be spent trying to determine where these live. Some of them feel like good script additions to the webpage repo.
