### ISSUE TITLE
Reduce matrix combinations in AppVeyor for non-Python packages to two (32 and 64 bits)

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/conda-smithy#160]
While creating packages for Graphviz in staged recipes (conda-forge/staged-recipes#568) I noticed that there are several matrix combinations that I think are useless in AppVeyor (because Graphviz is not a Python package):

https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2172

Worst in this case is that I'm just uncompressing a zip binary, and repackaging it as a conda package.

So I'd like to ask if we could reduce the matrix for non-Python packages to just 32 and 64 bit versions, with whatever conda Python version :-)

Pinging @msarahan about this one because he's the Windows expert ;-)

**Comment by msarahan** [comment]
This is fine as long as:

1. There are no library dependencies (or else you get into feature conflicts)
2. There are no libraries provided (or else you need to provide features, and each configuration)

**Comment by ccordoba12** [comment]
I see. So the problem doesn't seem too easy to solve :-)

**Comment by msarahan** [comment]
Not until we have a better way of allowing libraries built for different compilers to coexist in the same environment, and only be loaded by matching executables.  We're working on that, but it's still a long way off.

**Comment by pelson** [comment]
Thanks @ccordoba12 - I agree, there are matrix items in Appveyor which in this case are causing duplication. It is worth noting that the problem does not exist with a feedstock as we are able to inspect at render time what the dependencies are, but unfortunately we are forced to build each of the matrix items in staged-recipes as we do not have the ability to inspect the recipe before the AppVeyor matrix is defined. In short - not something that needs to be fixed in conda-smithy, and not something I think we can fix in staged-recipes (unless AppVeyor has the ability to programatically generate matrix items).

**Comment by ccordoba12** [comment]
If this problem doesn't exist in the feedstock, then I'm closing this one :-)
