### ISSUE TITLE
Call a `conda` subcommand instead of `cph`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#1698]
Currently we call `cph` by subcommand:

https://github.com/conda-forge/conda-smithy/blob/140a2729aa5aaf79eaa41d958e9422b1fbd49ce6/conda_smithy/configure_feedstock.py

However this can lead to [a wonky user experience if things are not installed as expected]( https://gitter.im/conda-forge/conda-forge.github.io?at=63856051326f06602c6d1268 ).

This might be better if we could use a `conda` subcommand instead of calling `cph`. Though one doesn't exist atm, this could be added and used in the future ( https://github.com/conda/conda-package-handling/issues/165 )

**Comment by mfisher87** [comment]
Struggling to find info on why I was getting `FileNotFoundError: [Errno 2] No such file or directory: 'cph'`; the gitter link above is not taking me to any relevant content.

It turned out it was because I had `conda-smithy` installed in my `base` environment, but had another environment activated. After `conda deactivate`, all was well.

**Comment by chrisburr** [comment]
I think I have a fix for this in https://github.com/conda-forge/conda-smithy/pull/1749/files
