### ISSUE TITLE
`swapfile_size` issue when building package

### ISSUE THREAD

**Issue by BEFH** [conda-forge/conda-smithy#1784]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

When I [updated the miller package](https://github.com/conda-forge/miller-feedstock/pull/22), conda-smithy added the following line to `.azure-pipelines/azure-pipelines-linux.yml`:

```
swapfile_size: 0GiB
```

This broke the build process:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=772817&view=results

```
/.azure-pipelines/azure-pipelines-linux.yml (Line: 15, Col: 3): Unexpected value 'swapfile_size'
```

There's some documentation about swapfile size here:
https://conda-forge.org/docs/maintainer/conda_forge_yml.html#azure

However, I did not change anything. In fact, there are no azure settings at all in conda_forge.yml.

I don't know where to go from here. If anyone has any advice, I am all ears.

### Installed packages

```shell
NA (this is conda-forge CI)
```

### Environment info

```shell
NA (this is conda-forge CI)
```

**Comment by jakirkham** [comment]
There was a bug in an older version of `conda-smithy`. This was fixed in PR ( https://github.com/conda-forge/conda-smithy/pull/1759 ), which is in version `3.25.1` and newer. So would just make sure to update `conda-smithy` (if you haven't already) and re-render

Closing since there is nothing more to do here. Though if you have questions, please feel free to ask here

**Comment by jakirkham** [comment]
Have asked the bot to re-render the `miller` feedstock: https://github.com/conda-forge/miller-feedstock/issues/23
