### ISSUE TITLE
Add azure option to install atl on Windows

### ISSUE THREAD

**Issue by traversaro** [conda-forge/conda-smithy#2062]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

It seems that now Windows Azure Pipelines images to not ship atl or anyhow require it to be re-installed manually (see https://github.com/actions/runner-images/issues/9873), that needs to be installed manually for recipes that need it, see:
* https://github.com/conda-forge/llvmdev-feedstock/pull/264#issuecomment-2128995491, https://github.com/conda-forge/llvmdev-feedstock/commit/221c9f3773f9cf17a95c34bc92316ca622488b65
* https://github.com/conda-forge/qt-main-feedstock/pull/269
* https://github.com/conda-forge/qt-main-feedstock/pull/288#issuecomment-2351442337

I may look into this eventually, but I need to get more familiar with conda-smithy codebase.

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by h-vetinari** [comment]
Thanks for opening. I had put this off because I had been hoping the images would be fixed in a reasonable timeline, but it doesn't look like that's happening.

Given that installing these components takes ~10min, I think we need to put this behind a config option, most likely in `conda-forge.yml`, and it would probably make sense to put this under
```
azure:
  settings_win:
```
