### ISSUE TITLE
Avoid impact of condarc

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#387]
In general, it is my preference to avoid the existence/content of `.condarc` to impact how a feedstock is rendered. If this were the case, issues such as https://github.com/conda-forge/conda-smithy/issues/281 should largely be avoided (I believe).

As ever: Happy to be convinced otherwise if there are compelling reasons to keep the behaviour.

**Comment by ocefpaf** [comment]
It seems that [this part](https://github.com/SciTools/conda-build-all/blob/master/conda_build_all/version_matrix.py#L182-L189) will choke when packages are bot available, like in the case below, while rerendering.
```

['cmake', 'hdf5 1.8.17|1.8.17.*', 'msinttypes', 'hdf4', 'curl', 'zlib 1.2.*', 'python 3.4*']
Package missing in current linux-64 channels: 
  - msinttypes
```

Ideally we still want to `rerender` for "`unsolvable_cases`"  cases because we know they are solvable in the conda-forge CI configuration.

I added a hack on my `conda-smithy` to work around that but maybe that is not the best solution. We should discuss the possibility of always pointing to pre-built index created by `conda-forge` and `defaults` channels to ensure the CIs configuration will be respected when re-rendering.

Does it makes sense? It would be quite faster too.

**Comment by jakirkham** [comment]
Yes, we are aware of this. We should also include `m2` as this is needed for Windows. However, that is going to make issue ( https://github.com/conda-forge/conda-smithy/issues/281 ) experienced by everyone. So we need someway to either check that channel only when we are re-rendering Windows or we need to otherwise address issue ( https://github.com/Anaconda-Platform/support/issues/76 ).

**Comment by jakirkham** [comment]
Yes, we are aware of this. We should also include `msys2` as this is needed for Windows. However, that is going to make issue ( https://github.com/conda-forge/conda-smithy/issues/281 ) experienced by everyone. So we need someway to either check that channel only when we are re-rendering Windows or we need to otherwise address issue ( https://github.com/Anaconda-Platform/support/issues/76 ).

**Comment by jakirkham** [comment]
The only compelling case I can think of is users outside `conda-forge` that use `conda-smithy` with their own custom channels that do not include the `conda-forge` channel. Hard coding these in `conda-smithy` would cause them issues. Maybe there could be an option for them to switch to using `.condarc` or maybe there is a better option that I'm not aware of. @shadowwalkersb , would you like to comment on this?

**Comment by shadowwalkersb** [comment]
Sorry, can't really say I'm following. 😕

**Comment by jjhelmus** [comment]
I've run into this issue in a few cases.  I believe it is possible to specify which channels to construct the conda index from manually so that the contents of `.condarc` are ignored.  Will try to put something together when I have some free time.  Perhaps defaulting to including the `conda-forge` and `defaults` channel in that order is best with an option to override these?

**Comment by jakirkham** [comment]
> Sorry, can't really say I'm following. 😕

The suggestion is that when `conda-smithy` re-renders it uses only packages from `conda-forge` and `defaults`. This could cause re-rendering issues for external feedstocks that have things in `requirements/build` that are not included in `conda-forge` and `defaults`. Hence why I pinged you as it may break things for you. So maybe you have some suggestions that will ensure this doesn't break your typical workflow (given you know more about it 😉).

**Comment by ocefpaf** [comment]
> I've run into this issue in a few cases.  I believe it is possible to specify which channels to construct the conda index from manually so that the contents of `.condarc` are ignored.  Will try to put something together when I have some free time.  Perhaps defaulting to including the `conda-forge` and `defaults` channel in that order is best with an option to override these?

@jjhelmus that is exactly what I ended up doing locally. But I am not sure that us the best solution as we still need to ship that index. Maybe we do not need the index at all as all the information for the re-rendering is in the recipe. Missing software will results in errors but I do not think there is the need to catch them while re-rendering. Does that makes sense @pelson?

**Comment by shadowwalkersb** [comment]
> Hence why I pinged you as it may break things for you. So maybe you have some suggestions that will ensure this doesn't break your typical workflow (given you know more about it 😉).

@jakirkham , in that case, thanks for the ping! Currently, I customize `conda-forge.yml`, where I have the following 
```
channels:
  sources: [shadow_walker, custom_channel/label/dependency, conda-forge]
  targets:
    - [custom_channel, main]

github:
  user_or_org: CustomChannel
  repo_name: custom_channel-feedstock
```

I would think, the changes proposed/discussed here wouldn't affect my setup. Or am I wrong?

**Comment by jakirkham** [comment]
That's a good point. If these changes use `channels/sources` for the re-rendering, it shouldn't break anyone's workflow. Does that seem reasonable to others?

**Comment by jakirkham** [comment]
Just put together PR ( https://github.com/conda-forge/conda-smithy/pull/401 ), which seems to do the trick. If people would like to try it out, would appreciate feedback.

**Comment by shadowwalkersb** [comment]
Now that this issue is sinking more and more, I think, local `.condarc` should be avoided completely. `.condarc` is for local usage and is a result of more of personal projects. I imagine, feedstock maintainers often deal with projects that they may not use locally. So, anything feedstock related should be kept decoupled from local settings. Everything feedstock related should be handled in `conda-forge.yml` isolating it from local environments.

**Comment by jakirkham** [comment]
That should be what PR ( https://github.com/conda-forge/conda-smithy/pull/401 ) does. Do you mind taking a look if you have some time, @shadowwalkersb ?
