### ISSUE TITLE
Recipe rerendered with conda smithy 1.6.1 fails to build on appveyor

### ISSUE THREAD

**Issue by astaric** [conda-forge/conda-smithy#396]
After rerendering a recipe with conda smithy 1.6.1, it no longer builds on appveyor. The old version (rendered with smithy 1.5.1) used to build successfully, but only built against numpy 1.11

The recipe has numpy x.x in dependencies, the error reported is:
```
...Error: The following specifications were found to be in conflict:
  - numpy 1.10*
  - orange3 3.3.8 np110py34_4
```

failing build: https://ci.appveyor.com/project/conda-forge/orange3-feedstock/build/1.0.36
last successful build: https://ci.appveyor.com/project/conda-forge/orange3-feedstock/build/1.0.33
changes: https://github.com/conda-forge/orange3-feedstock/pull/15

**Comment by jakirkham** [comment]
Sorry @astaric , but that re-rendering looks to be correct. The response from the solver while potentially true is not exactly insightful. I would look at each of your dependencies and make sure that either they don't use `numpy x.x`; or if they do, verify they have a version built against `numpy` version `1.10`. If you find any that don't, it would be good to raise issues on those feedstocks so that we can get that fixed.

**Comment by astaric** [comment]
As far as I can tell, scipy and scikit-learn on conda-forge do not provide windows builds, so the ones from default channel are used (which are only built against numpy 1.11).

Thanks for your help, I'll update the recipe to only build with numpy 1.11 on windows.

**Comment by jakirkham** [comment]
To get a full listing of things from defaults, please see the following for [64-bit]( https://repo.continuum.io/pkgs/free/win-64 ) and [32-bit]( https://repo.continuum.io/pkgs/free/win-32 ). Maybe that will help.

**Comment by jakirkham** [comment]
To get a full listing of Windows packages from defaults, please see the following for [64-bit]( https://repo.continuum.io/pkgs/free/win-64 ) and [32-bit]( https://repo.continuum.io/pkgs/free/win-32 ). Maybe that will help.
