### ISSUE TITLE
Incorrectly interpreting `skip: True  # [not py35]` line

### ISSUE THREAD

**Issue by tadeu** [conda-forge/conda-smithy#426]
When using `conda smithy rerender` on a [recipe that contains this line](https://github.com/tadeu/doxygen-feedstock/blob/cfe9ca878d784f0c941fd15bbb4bf0b25bb321ce/recipe/meta.yaml#L29) (`skip: True  # [not py35]`), it is removing `appveyor.yml` and `.travis.yml`, as if it had to skip all platforms.

**Comment by scopatz** [comment]
I am seeing something similar where a recipe (cymetric) with `skip: True  # [win or py34]` will still generate Python 3.4 hooks after a `conda smithy rerender`

**Comment by scopatz** [comment]
Oddly for me, it is also keeping the windows hooks, even though it shouldn't

**Comment by jakirkham** [comment]
Interesting. Also what happened to the `build/features` in that commit @tadeu ?

**Comment by jakirkham** [comment]
Do you have a PR or commit, @scopatz ?

**Comment by jakirkham** [comment]
Also please both share info from `.condarc` and any other relevant channel configs.

**Comment by jakirkham** [comment]
> Oddly for me, it is also keeping the windows hooks, even though it shouldn't

This is intentional and correct. The webhooks should never be touched by re-rendering. Most users don't have access to these. So that would not be a reliable way of disabling CIs.

Instead we tell AppVeyor and Travis CI to not build if their CI config file is missing. This setting is enabled when feedstocks are generated at `staged-recipes` and is part of CI registration in `conda-smithy`. Hence those CI config files are removed and the CI does not build as a result (barring some CI bug). CircleCI is a different story, but I digress. Moral of the story, the webhooks should always be there, but files come and go.

Please let me know if you have more questions on this, @scopatz.

**Comment by scopatz** [comment]
Thanks @jakirkham, as you guessed this was the cymetric issue. My problems are now solved, thanks!  Should I open up an issue here about linting duplicate tags?

**Comment by jakirkham** [comment]
Glad to help. That sounds like a great idea! Please do. 😄

**Comment by jakirkham** [comment]
Writing this to summarize my thoughts after digging into these cases. After looking at both of these cases, I agree that there are things we can do (much) better, but the things wrong are not the re-rendering.

In your case, @tadeu, I think `conda-smithy`, `conda-build-all` maybe even `conda-build` should complain that a `py` selector is being used when `python` is not a requirement. It results in a strange skip platform case that is not obvious initially. I don't know if that is enough of a hint, but it would at least get one to poke around in the right places. Not sure if this warning should come out of the linter or `conda-smithy` directly. Would be happy to discuss all of this with you and others in a new issue.

As for your case @scopatz, I agree that we should be complaining about two `build` sections. Sadly it is too easy for human eyes to gloss over small duplications like this. Thankfully bots are unrelenting. So hopefully that will help us catch this sort of issue sooner. Definitely please raise an issue on this. I can't say this is the first time a duplicate `build` section slipped through.

If I have missed something, feel free to nudge me and we can reopen. Otherwise I'm closing this out. Though please do raise new issues about these problems so we can discuss how to better communicate what is off.

**Comment by tadeu** [comment]
> Interesting. Also what happened to the build/features in that commit @tadeu ?

@jakirkham I've removed it, since `doxygen` doesn't seem to need a runtime (it is copied from the binary distribution, which doesn't include any runtime)

**Comment by tadeu** [comment]
> In your case, @tadeu, I think conda-smithy, conda-build-all maybe even conda-build should complain that a py selector is being used when python is not a requirement. It results in a strange skip platform case that is not obvious initially. I don't know if that is enough of a hint, but it would at least get one to poke around in the right places. Not sure if this warning should come out of the linter or conda-smithy directly. Would be happy to discuss all of this with you and others in a new issue.

@jakirkham I agree, thanks for looking into this. The `not py35` is there just for ensuring it will not build more than one package with the same name, but I agree it seems weird if there'd no requirement for python.
