### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#513]
We should do a v2.3.1 release as mentioned in https://github.com/conda-forge/conda-smithy/pull/511

**Comment by jakirkham** [comment]
Thanks for the reminder @isuruf. Will do so when I have a bit more time.

**Comment by isuruf** [comment]
Here's a branch https://github.com/isuruf/conda-smithy/tree/v2.3.x
There were 3 pull requests since last release #510 #511 #508
Kept #510 and #508 and removed #511

**Comment by jakirkham** [comment]
Thanks @isuruf.

I backported these changes in PR ( https://github.com/conda-forge/conda-smithy/pull/514 ) and PR ( https://github.com/conda-forge/conda-smithy/pull/515 ) to the `release/2.3.x` branch. Took both of those PRs and squashed them into single commits that I cherry-picked onto that branch. The commit history is recorded in each commit.

Did a diff between my work and your work locally and they seem to be the same. Also did a diff between `master` to verify that I did not get the template changes by accident and it looks clean. Further double checked the branch had no differences to template files (or feedstock content related changes) since `v2.3.0`. All of this came up clean.

Though wouldn't mind if you wanted to double check it. 😉

**Comment by isuruf** [comment]
Looks good to me. Let's make a release

**Comment by jakirkham** [comment]
Will be released with the merge of PR ( https://github.com/conda-forge/conda-smithy-feedstock/pull/77 ).

**Comment by jakirkham** [comment]
Kind of unrelated. When I make a tag, normally I use `git tag -a`, which provides an annotated tag. Then just add the changelog information in there. That way it is accessible from `git` as well. Also it makes it pretty easy to publish the exact same information on GitHub. Plus `git describe` works more nicely with it.

**Comment by isuruf** [comment]
Ah, will do next time. I used the GitHub UI to create a release which doesn't do an annotated tag.

**Comment by jakirkham** [comment]
No worries. Yeah unfortunately GitHub's UI doesn't do it right. (sigh)
