### ISSUE TITLE
Conda version and conda-smithy

### ISSUE THREAD

**Issue by ericmjl** [conda-forge/conda-smithy#519]
I tried re-rendering the `legit` feedstock with conda-smithy, and while everything seems okay so far, I get the following issue: 

```bash
You appear to be using conda 4.3.18, but conda-smithy 2.3.1 is
currently only compatible with conda versions < 4.3.
```

Is this something I should be worried about?

**Comment by jakirkham** [comment]
Yes, `conda` 4.3 is not supported by `conda-build-all`, which `conda-smithy` requires. Until that is fixed, one must downgrade `conda` to 4.2 manually. The best we could do was add this message due to difficulties with the `conda` solver and setting upper bounds on dependency versions.

xref: https://github.com/SciTools/conda-build-all/pull/83
