### ISSUE TITLE
numpy 1.13 and python 3.6 support after re-render

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-smithy#538]
It seems that numpy 1.13 combined with python 3.6 support are not part of the re-render?
Example https://github.com/conda-forge/pyfai-feedstock/pull/12

**Comment by isuruf** [comment]
Do all the dependencies have numpy 1.13 and python 3.6 support?

**Comment by jakirkham** [comment]
Given we have re-rendered other things and added Python 3.6 and NumPy 1.13 without issue, I'm inclined to agree with @isuruf that this is a dependency issue. Took a quick glance and `fabio` sticks out to me as potentially problematic.

Going to close this out as it does not appear to be a `conda-smithy` issue, happy to reopen though if that turns out not to be the case.
