### ISSUE TITLE
Add the ability to re-direct built output

### ISSUE THREAD

**Issue by pelson** [conda-forge/conda-smithy#59]
It would be neat if we could add some metadata to the recipe, and that automatically diverted the destination channel.

i.e.

```
extra:
   channels:
      - testing
```

And this ended up on ```conda-forge/channel/testing``` rather than the default of ```conda-forge/channel/main```.

There is some detail here about whether this actually belongs in the recipe, or the conda-forge.yaml file...

**Comment by JanSchulz** [comment]
This is already in #56 as an option in the conda-forge.yml file: https://github.com/conda-forge/conda-smithy/pull/56/files#diff-d780142cb5b4b67f7a8fd097e056bba6R37 

IMO it shouldn't go to the meta.yml, as that would be kind of like food recipes which would state as a final step, that the product should be shipped to me so that I can distribute it :-)

**Comment by JanSchulz** [comment]
Oh, and actually you can already do it with the conda-forge.yml config file today: https://github.com/conda-forge/conda-smithy/pull/56/files#diff-d780142cb5b4b67f7a8fd097e056bba6R37

**Comment by pelson** [comment]
> Oh, and actually you can already do it with the conda-forge.yml config file today

Thanks @JanSchulz. You know sometimes I go to StackOverflow for questions I don't know the answer to, find the answer and think "this guy knows what he's talking about", then realise *I* wrote the answer. What it is to have a memory like a :fish: :smile:

**Comment by JanSchulz** [comment]
:-)

**Comment by pelson** [comment]
done.
