### ISSUE TITLE
Lint: Check that the latest version is packaged

### ISSUE THREAD

**Issue by jankatins** [conda-forge/conda-smithy#61]
In most cases: conda package name = pypi name, so it should be possible to check if there is a new release on pypi. 

https://github.com/bmwant21/leak

**Comment by pelson** [comment]
Nice idea. I'm not convinced it is a conda-smithy issue. I'd expect the question "is there a newer version of package X on PyPi than on channel Y" to be more broadly useful than just for conda-forge.

**Comment by JanSchulz** [comment]
@pelson That's actually true for the whole of `conda lint` :-)

**Comment by pelson** [comment]
> That's actually true for the whole of conda lint :-)

Agreed. The only slight defense of where it currently lives is that ```conda lint``` is a very specific implementation of the conda-forge recipe quality policy. In general though, I'm completely supportive of ```conda lint``` being its own thing.

**Comment by JanSchulz** [comment]
Another lib/program which does this: https://github.com/bboe/update_checker

**Comment by pelson** [comment]
I also head of https://requires.io/ which might be interesting to dig into. Do you want to lead on the auto version checking @JanSchulz?

**Comment by JanSchulz** [comment]
I can do that, but no idea how long that will take (I'm currently doing R stuff for my PhD :-/). 

* [ ] package https://github.com/bmwant/leak/
* [ ] write a check which basically gets the version from the metadata and runs our own version of  `https://github.com/bmwant/leak/blob/master/leak/main.py#L88`.

**Comment by jakirkham** [comment]
Adding [VersionEye]( https://www.versioneye.com/ ) to the list of tools like this.

**Comment by jakirkham** [comment]
So there is a script @jjhelmus contributed, which does this sort of thing. Also there is `feedstockrot` that @RSully contributed, which does a similar thing. References below. Maybe instead of thinking about the linter we should consolidate those two efforts first and then leverage the API of the resulting tool in the linter (assuming that is something we still want).

xref: https://github.com/conda-forge/conda-forge.github.io/pull/197
xref: https://github.com/conda-forge/staged-recipes/pull/1261
xref: https://github.com/conda-forge/feedstockrot-feedstock
xref: https://github.com/axiom-data-science/feedstockrot

**Comment by CJ-Wright** [comment]
Does the autotick bot fix this? Can we close?

**Comment by jakirkham** [comment]
Agreed. Closing. If someone thinks otherwise, please raise a new issue.
