### ISSUE TITLE
rever release notes

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/conda-smithy#745]
@scopatz: The new `rever` release process seems to not be making useful release notes on https://github.com/conda-forge/conda-smithy/releases. The last few just have whatever the last commit message was, versus the previous ones that actually had a list of changes. Not sure if that was hand-generated before or automatic somehow, but at least if it was automatic, that was better than the current setup. :)

Edit: actually it looks like they were hand-written before. A list of the merged PRs and their titles, or something like that, would be far more useful than just last-commit-message (which is typically either meaningless or even misleading, because it only mentions the most recent change).

**Comment by CJ-Wright** [comment]
We should use the `rever` news system! This will auto generate the changelog with information put in during the PR process.

**Comment by jakirkham** [comment]
Thanks for opening this, @dougalsutherland. Completely agree.

Figured `rever` had solutions for these kinds of things. For those of us who don't know, @CJ-Wright, could you please explain/point to info on the news system?

**Comment by scopatz** [comment]
Hi @dougalsutherland @jakirkham, I didn't add the rever changelog features originally because I wanted to perform a minimal change, and the current changelog is hand-written anyway. 

You can read about how the system works at https://regro.github.io/rever-docs/devguide.html#changelog, and rever and xonsh and other projects use this system. You can see the results at https://github.com/regro/rever/releases and  https://github.com/xonsh/xonsh/releases. But basically the idea is: 

* With each PR, the author adds a changelog entry to a known place (the `news/` dir)
* Changelog entries are given in their own file for each branch, so there aren't constant conflicts merging into master
* At release time, rever combines the entries, adds them to the global changelog and the GitHub Release

This system shifts the responsibility for writing the changelog to the authors at the time of PR, rather than the release manager at the time of release. I personally have found this to be a **major** advantage, but didn't want to impose this without community input. 

In xonsh, we even have a bot that checks that a news item has been added or modified!

I am happy to add this feature to conda-smithy (and other conda-forge projects) if folks are interested.

**Comment by dougalsutherland** [comment]
That sounds like a good system to me. 👍 on using it here.

**Comment by CJ-Wright** [comment]
I've implemented the `rever` news system in #750. I also added a news entry which we could potentially use as an example. Do you mind if I close?

**Comment by jakirkham** [comment]
Thanks @CJ-Wright.
