### ISSUE TITLE
Strange Windows badge

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-smithy#777]
Appears the AppVeyor badge can't check the Windows build status, but the link to the AppVeyor project works fine. Any ideas what is going on?

<img width="1552" alt="screen shot 2018-05-16 at 18 07 29" src="https://user-images.githubusercontent.com/3019665/40151325-1d93984e-5934-11e8-952b-5f780e24b5ef.png">

ref: https://github.com/conda-forge/backports.lzma-feedstock#current-build-status

**Comment by jakirkham** [comment]
cc @epruesse

**Comment by epruesse** [comment]
The link and the image are separate, the URL that isn't working is this one:

https://img.shields.io/appveyor/ci/conda-forge/backports.lzma-feedstock/master.svg

Not sure why. Other shields.io appveyor badges seem to be working. Is there maybe something at AppVeyor you have to enable now so that the API is enabled for conda-forge? Otherwise, the best I can think of is creating an issue at shields itself, asking about this.

**Comment by jakirkham** [comment]
Thanks for taking a look @epruesse.

Think the issue is the `.` should be `-`. For example, the URL below works.

https://img.shields.io/appveyor/ci/conda-forge/backports-lzma-feedstock/master.svg

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-smithy/blob/master/conda_smithy/templates/README.md.tmpl#L37
should be 
```
[![Windows]({{ shield }}appveyor/ci/{{ github.user_or_org }}/{{ appveyor_url_name }}/master.svg?label=Windows)](https://ci.appveyor.com/project/{{ github.user_or_org }}/{{ appveyor_url_name }}/branch/master)
```
instead of 
```
[![Windows]({{ shield }}appveyor/ci/{{ github.user_or_org }}/{{ github.repo_name }}/master.svg?label=Windows)](https://ci.appveyor.com/project/{{ github.user_or_org }}/{{ appveyor_url_name }}/branch/master)
```

**Comment by jakirkham** [comment]
Added PR ( https://github.com/conda-forge/conda-smithy/pull/883 ) to fix this. Seems to resolve the issue based on testing locally.
