### ISSUE TITLE
New conda-smithy disables all builds

### ISSUE THREAD

**Issue by dstansby** [conda-forge/conda-smithy#810]
I've just updated to `conda-smith` 3.1.6, and running `conda smithy rerender` disables all my builds. I'm guessing this is something to do with the line `skip: true  # [not py36]` in my `meta.yml`, which should mean only builds on Python 3.6 are done.

See https://github.com/conda-forge/heliopy-feedstock/pull/3 for an example of everything being disabled.

**Comment by dstansby** [comment]
It looks like the problem is
```
build:
  skip: true  # [not py36]
```
is skipping everything, instead of anything that isn't python 3.6 builds.

**Comment by jakirkham** [comment]
Hmm...so I didn't see that line in the recipe. Am I missing something?

Would also suggest replacing `requirements/build` with `requirements/host`.

**Comment by dstansby** [comment]
I got rid of it to fix the problem, but it should still be there in the PR I linked to. Is the code I posted to only do python 3.6 builds the correct code in theory?

**Comment by dougalsutherland** [comment]
@dstansby The problem is that you have `python` in `host` and not in `run`, which with the new version of `conda-build` says "I only need Python at build time (and don't care about the version), I don't care about it at runtime." You need `python` in `run` to tell conda-build to make different versions of the package for different Python versions.

Sending a PR to fix it to `heliopy`.

**Comment by jakirkham** [comment]
Thanks @dougalsutherland :)
