### ISSUE TITLE
Conda-forge re-rendered turned off builds for visidata-feedstock

### ISSUE THREAD

**Issue by anjakefala** [conda-forge/conda-smithy#867]
Hello! =)

I used the automated conda-forge re-rendering services, and it seems to have turned off all of the builds for the [visidata-feedstock](https://github.com/conda-forge/visidata-feedstock) package:

https://github.com/conda-forge/visidata-feedstock/commit/c7f0198fcbe2b734cbfb16ba4a618032152aa637

I would appreciate any help in figuring out how to get the build working again. The only changes I made to the meta.yml were version and sha-256.

**Comment by scopatz** [comment]
Hi there @anjakefala!

I think the issue is in the `meta.yaml`  Specifcically the line:

```yaml
  skip: True  # [py<34]
```

The issue is that the selector `py` has been pretty unstable in that sometimes it is a string and sometime it is an int. So it is possible that `py<34` is always True one more recent versions of conda build and therefore everything is getting skipped when you rerendered.

I would suggest changing this to be:

```yaml
  skip: True  # [py27]
```

This is effectively the same thing since conda-forge has never built any Python <3.4.  I hope this helps!

**Comment by anjakefala** [comment]
Thanks @scopatz! I think I *did* pick up that py<34 somewhere, so I will take a quick look through your docs and ensure that it was not from there.

=)

Things seem fine now. Thanks for your help!
