### ISSUE TITLE
update-cb3: added a second build section to the tectonic feedstock

### ISSUE THREAD

**Issue by pkgw** [conda-forge/conda-smithy#869]
[Here](https://github.com/conda-forge/tectonic-feedstock/pull/8). It added a second `build` section somehow!

Initially reported [here](https://github.com/regro/cf-scripts/issues/316), but redirected.

**Comment by ocefpaf** [comment]
@pkgw `update-cb3` is a temporary hack and we are not really investing a lot of time to fix it. I guess that the issue you are reporting only happens when we run it twice, is that correct?

BTW we would review and merge a PR fixing that but I guess that we are almost done with the updates (ping @CJ-Wright who has the numbers) and maybe it is not worth it.

**Comment by pkgw** [comment]
Yeah, that makes sense. I imagine that the tool has mostly done its work by now so probably this is a weird corner case. I'll go ahead and close, but if it comes up more, now you know.
