### ISSUE TITLE
Azure: conda-forge build setup scripts are not sourced.

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-smithy#963]
This means the env variables set in those scripts are lost.

**Comment by mariusvniekerk** [comment]
A better approach for this behavior would be to have those scripts write an env vars file that can be sourced in a cross-platform way without needing to rely on the relatively fragile templating we do presently.  This would also help solve the issue caused by environment variables not persisting past stages on azure.  

Lastly it would simplify our rendering code as we would not need to do anything special for the various backends

**Comment by isuruf** [comment]
Or we can move the file to a activate script so that conda will source them

**Comment by isuruf** [comment]
Moved to activate
